compila_1:
	gcc src/prog1.c -o bin/prog1

run_1:
	bin/prog1

compila_2:
	gcc src/prog2.c -o bin/prog2

run_2:
	bin/prog2

compila_3:
	gcc src/prog3.c -o bin/prog3

run_3:
	bin/prog3

clean:
	rm bin/*
